providers:
  openai:
    model: "gpt-4-turbo"
    max_tokens: 2000
    temperature: 0.7
  deepseek:
    model: "deepseek-v2"
    technical_boost: true

blending:
  default_mode: "balanced"
  strategies:
    - "weighted_average"
    - "semantic_merge"

logging:
  level: "INFO"
  file: "logs/ai_core.log"
